[phases.setup]
nixPkgs = ["python312", "python312Packages.setuptools", "python312Packages.pip", "python312Packages.distutils"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmds = ["python main.py"]
